const lookupTimezone = {
    'AFGHANISTAN': 'Asia/Kabul', 'ALBANIA': 'Europe/Tirane', 'ALGERIA': 'Africa/Algiers',
    'ANDORRA': 'Europe/Andorra', 'ANGOLA': 'Africa/Luanda', 'ARGENTINA': 'America/Argentina/Buenos_Aires',
    'ARMENIA': 'Asia/Yerevan', 'AUSTRALIA': 'Australia/Sydney', 'AUSTRIA': 'Europe/Vienna',
    'AZERBAIJAN': 'Asia/Baku', 'BAHAMAS': 'America/Nassau', 'BAHRAIN': 'Asia/Bahrain',
    'BANGLADESH': 'Asia/Dhaka', 'BARBADOS': 'America/Barbados', 'BELARUS': 'Europe/Minsk',
    'BELGIUM': 'Europe/Brussels', 'BELIZE': 'America/Belize', 'BENIN': 'Africa/Porto-Novo',
    'BHUTAN': 'Asia/Thimphu', 'BOLIVIA': 'America/La_Paz', 'BOSNIA AND HERZEGOVINA': 'Europe/Sarajevo',
    'BOTSWANA': 'Africa/Gaborone', 'BRAZIL': 'America/Sao_Paulo', 'BRUNEI': 'Asia/Brunei',
    'BULGARIA': 'Europe/Sofia', 'BURKINA FASO': 'Africa/Ouagadougou', 'BURUNDI': 'Africa/Bujumbura',
    'CAMBODIA': 'Asia/Phnom_Penh', 'CAMEROON': 'Africa/Douala', 'CANADA': 'America/Toronto',
    'CAPE VERDE': 'Atlantic/Cape_Verde', 'CENTRAL AFRICAN REPUBLIC': 'Africa/Bangui',
    'CHAD': 'Africa/Ndjamena', 'CHILE': 'America/Santiago', 'CHINA': 'Asia/Shanghai',
    'COLOMBIA': 'America/Bogota', 'COMOROS': 'Indian/Comoro', 'CONGO': 'Africa/Brazzaville',
    'CONGO (DRC)': 'Africa/Kinshasa', 'COSTA RICA': 'America/Costa_Rica',
    'CROATIA': 'Europe/Zagreb', 'CUBA': 'America/Havana', 'CYPRUS': 'Asia/Nicosia',
    'CZECH REPUBLIC': 'Europe/Prague', 'DENMARK': 'Europe/Copenhagen', 'DJIBOUTI': 'Africa/Djibouti',
    'DOMINICA': 'America/Dominica', 'DOMINICAN REPUBLIC': 'America/Santo_Domingo',
    'ECUADOR': 'America/Guayaquil', 'EGYPT': 'Africa/Cairo', 'EL SALVADOR': 'America/El_Salvador',
    'EQUATORIAL GUINEA': 'Africa/Malabo', 'ERITREA': 'Africa/Asmara', 'ESTONIA': 'Europe/Tallinn',
    'ESWATINI': 'Africa/Mbabane', 'ETHIOPIA': 'Africa/Addis_Ababa', 'FIJI': 'Pacific/Fiji',
    'FINLAND': 'Europe/Helsinki', 'FRANCE': 'Europe/Paris', 'GABON': 'Africa/Libreville',
    'GAMBIA': 'Africa/Banjul', 'GEORGIA': 'Asia/Tbilisi', 'GERMANY': 'Europe/Berlin',
    'GHANA': 'Africa/Accra', 'GREECE': 'Europe/Athens', 'GREENLAND': 'America/Nuuk',
    'GRENADA': 'America/Grenada', 'GUATEMALA': 'America/Guatemala', 'GUINEA': 'Africa/Conakry',
    'GUINEA-BISSAU': 'Africa/Bissau', 'GUYANA': 'America/Guyana', 'HAITI': 'America/Port-au-Prince',
    'HONDURAS': 'America/Tegucigalpa', 'HONG KONG': 'Asia/Hong_Kong', 'HUNGARY': 'Europe/Budapest',
    'ICELAND': 'Atlantic/Reykjavik', 'INDIA': 'Asia/Kolkata', 'INDONESIA': 'Asia/Jakarta',
    'IRAN': 'Asia/Tehran', 'IRAQ': 'Asia/Baghdad', 'IRELAND': 'Europe/Dublin',
    'ISRAEL': 'Asia/Jerusalem', 'ITALY': 'Europe/Rome', 'IVORY COAST': 'Africa/Abidjan',
    'JAMAICA': 'America/Jamaica', 'JAPAN': 'Asia/Tokyo', 'JORDAN': 'Asia/Amman',
    'KAZAKHSTAN': 'Asia/Almaty', 'KENYA': 'Africa/Nairobi', 'KIRIBATI': 'Pacific/Tarawa',
    'KOSOVO': 'Europe/Belgrade', 'KUWAIT': 'Asia/Kuwait', 'KYRGYZSTAN': 'Asia/Bishkek',
    'LAOS': 'Asia/Vientiane', 'LATVIA': 'Europe/Riga', 'LEBANON': 'Asia/Beirut',
    'LESOTHO': 'Africa/Maseru', 'LIBERIA': 'Africa/Monrovia', 'LIBYA': 'Africa/Tripoli',
    'LIECHTENSTEIN': 'Europe/Vaduz', 'LITHUANIA': 'Europe/Vilnius', 'LUXEMBOURG': 'Europe/Luxembourg',
    'MACAU': 'Asia/Macau', 'MADAGASCAR': 'Indian/Antananarivo', 'MALAWI': 'Africa/Blantyre',
    'MALAYSIA': 'Asia/Kuala_Lumpur', 'MALDIVES': 'Indian/Maldives', 'MALI': 'Africa/Bamako',
    'MALTA': 'Europe/Malta', 'MARSHALL ISLANDS': 'Pacific/Majuro', 'MAURITANIA': 'Africa/Nouakchott',
    'MAURITIUS': 'Indian/Mauritius', 'MEXICO': 'America/Mexico_City', 'MICRONESIA': 'Pacific/Pohnpei',
    'MOLDOVA': 'Europe/Chisinau', 'MONACO': 'Europe/Monaco', 'MONGOLIA': 'Asia/Ulaanbaatar',
    'MONTENEGRO': 'Europe/Podgorica', 'MOROCCO': 'Africa/Casablanca', 'MOZAMBIQUE': 'Africa/Maputo',
    'MYANMAR': 'Asia/Yangon', 'NAMIBIA': 'Africa/Windhoek', 'NAURU': 'Pacific/Nauru',
    'NEPAL': 'Asia/Kathmandu', 'NETHERLANDS': 'Europe/Amsterdam', 'NEW ZEALAND': 'Pacific/Auckland',
    'NICARAGUA': 'America/Managua', 'NIGER': 'Africa/Niamey', 'NIGERIA': 'Africa/Lagos',
    'NORTH KOREA': 'Asia/Pyongyang', 'NORTH MACEDONIA': 'Europe/Skopje', 'NORWAY': 'Europe/Oslo',
    'OMAN': 'Asia/Muscat', 'PAKISTAN': 'Asia/Karachi', 'PALAU': 'Pacific/Palau',
    'PALESTINE': 'Asia/Gaza', 'PANAMA': 'America/Panama', 'PAPUA NEW GUINEA': 'Pacific/Port_Moresby',
    'PARAGUAY': 'America/Asuncion', 'PERU': 'America/Lima', 'PHILIPPINES': 'Asia/Manila',
    'POLAND': 'Europe/Warsaw', 'PORTUGAL': 'Europe/Lisbon', 'PUERTO RICO': 'America/Puerto_Rico',
    'QATAR': 'Asia/Qatar', 'ROMANIA': 'Europe/Bucharest', 'RUSSIA': 'Europe/Moscow',
    'RWANDA': 'Africa/Kigali', 'SAMOA': 'Pacific/Apia', 'SAN MARINO': 'Europe/San_Marino',
    'SAUDI ARABIA': 'Asia/Riyadh', 'SENEGAL': 'Africa/Dakar', 'SERBIA': 'Europe/Belgrade',
    'SEYCHELLES': 'Indian/Mahe', 'SIERRA LEONE': 'Africa/Freetown', 'SINGAPORE': 'Asia/Singapore',
    'SLOVAKIA': 'Europe/Bratislava', 'SLOVENIA': 'Europe/Ljubljana', 'SOLOMON ISLANDS': 'Pacific/Guadalcanal',
    'SOMALIA': 'Africa/Mogadishu', 'SOUTH AFRICA': 'Africa/Johannesburg', 'SOUTH KOREA': 'Asia/Seoul',
    'SOUTH SUDAN': 'Africa/Juba', 'SPAIN': 'Europe/Madrid', 'SRI LANKA': 'Asia/Colombo',
    'SUDAN': 'Africa/Khartoum', 'SURINAME': 'America/Paramaribo', 'SWEDEN': 'Europe/Stockholm',
    'SWITZERLAND': 'Europe/Zurich', 'SYRIA': 'Asia/Damascus', 'TAIWAN': 'Asia/Taipei',
    'TAJIKISTAN': 'Asia/Dushanbe', 'TANZANIA': 'Africa/Dar_es_Salaam', 'THAILAND': 'Asia/Bangkok',
    'TIMOR-LESTE': 'Asia/Dili', 'TOGO': 'Africa/Lome', 'TONGA': 'Pacific/Tongatapu',
    'TRINIDAD AND TOBAGO': 'America/Port_of_Spain', 'TUNISIA': 'Africa/Tunis', 'TURKEY': 'Europe/Istanbul',
    'TURKMENISTAN': 'Asia/Ashgabat', 'TUVALU': 'Pacific/Funafuti', 'UGANDA': 'Africa/Kampala',
    'UKRAINE': 'Europe/Kyiv', 'UNITED ARAB EMIRATES': 'Asia/Dubai', 'UNITED KINGDOM': 'Europe/London',
    'UNITED STATES': 'America/New_York', 'URUGUAY': 'America/Montevideo', 'UZBEKISTAN': 'Asia/Tashkent',
    'VANUATU': 'Pacific/Efate', 'VATICAN CITY': 'Europe/Vatican', 'VENEZUELA': 'America/Caracas',
    'VIETNAM': 'Asia/Ho_Chi_Minh', 'YEMEN': 'Asia/Aden', 'ZAMBIA': 'Africa/Lusaka',
    'ZIMBABWE': 'Africa/Harare'
};

const lookupCountry = Object.keys(lookupTimezone).sort();

const lookupTimezoneState = {
    'UNITED STATES': { CA: 'America/Los_Angeles', WA: 'America/Los_Angeles', OR: 'America/Los_Angeles', NV: 'America/Los_Angeles', AZ: 'America/Phoenix', CO: 'America/Denver', UT: 'America/Denver', NM: 'America/Denver', MT: 'America/Denver', WY: 'America/Denver', ID: 'America/Boise', TX: 'America/Chicago', IL: 'America/Chicago', MN: 'America/Chicago', WI: 'America/Chicago', MO: 'America/Chicago', LA: 'America/Chicago', OK: 'America/Chicago', KS: 'America/Chicago', NE: 'America/Chicago', IA: 'America/Chicago', AR: 'America/Chicago', MS: 'America/Chicago', AL: 'America/Chicago', TN: 'America/Chicago', ND: 'America/Chicago', SD: 'America/Chicago', NY: 'America/New_York', FL: 'America/New_York', PA: 'America/New_York', OH: 'America/New_York', GA: 'America/New_York', NC: 'America/New_York', SC: 'America/New_York', VA: 'America/New_York', MA: 'America/New_York', NJ: 'America/New_York', MD: 'America/New_York', ME: 'America/New_York', KY: 'America/New_York', WV: 'America/New_York', VT: 'America/New_York', NH: 'America/New_York', RI: 'America/New_York', DE: 'America/New_York', CT: 'America/New_York', DC: 'America/New_York', MI: 'America/Detroit', IN: 'America/Indiana/Indianapolis', HI: 'Pacific/Honolulu', AK: 'America/Anchorage' },
    'CANADA': { BC: 'America/Vancouver', YT: 'America/Whitehorse', AB: 'America/Edmonton', NT: 'America/Yellowknife', SK: 'America/Regina', MB: 'America/Winnipeg', NU: 'America/Iqaluit', ON: 'America/Toronto', QC: 'America/Toronto', NS: 'America/Halifax', NB: 'America/Halifax', PE: 'America/Halifax', NL: 'America/St_Johns' },
    'AUSTRALIA': { WA: 'Australia/Perth', NT: 'Australia/Darwin', SA: 'Australia/Adelaide', QLD: 'Australia/Brisbane', NSW: 'Australia/Sydney', VIC: 'Australia/Melbourne', TAS: 'Australia/Hobart', ACT: 'Australia/Sydney' },
    'BRAZIL': { SP: 'America/Sao_Paulo', RJ: 'America/Sao_Paulo', MG: 'America/Sao_Paulo', RS: 'America/Sao_Paulo', PR: 'America/Sao_Paulo', SC: 'America/Sao_Paulo', DF: 'America/Sao_Paulo', BA: 'America/Bahia', PE: 'America/Recife', CE: 'America/Fortaleza', AM: 'America/Manaus', MT: 'America/Cuiaba', MS: 'America/Campo_Grande', AC: 'America/Rio_Branco' },
    'RUSSIA': { MOW: 'Europe/Moscow', SPE: 'Europe/Moscow', KGD: 'Europe/Kaliningrad', SVE: 'Asia/Yekaterinburg', NVS: 'Asia/Novosibirsk', IRK: 'Asia/Irkutsk', PRI: 'Asia/Vladivostok', KAM: 'Asia/Kamchatka' },
    'MEXICO': { BCN: 'America/Tijuana', BCS: 'America/Mazatlan', SON: 'America/Hermosillo', CHH: 'America/Chihuahua', ROO: 'America/Cancun', CMX: 'America/Mexico_City' },
    'INDONESIA': { JK: 'Asia/Jakarta', BA: 'Asia/Makassar', PA: 'Asia/Jayapura' },
    'KAZAKHSTAN': { ALA: 'Asia/Almaty', AKT: 'Asia/Aqtobe' },
    'SPAIN': { CN: 'Atlantic/Canary' },
    'PORTUGAL': { AZ: 'Atlantic/Azores', MA: 'Atlantic/Madeira' },
    'CHILE': { MAG: 'America/Punta_Arenas', IPC: 'Pacific/Easter' },
    'ECUADOR': { GAL: 'Pacific/Galapagos' },
    'GREENLAND': { TH: 'America/Thule', SC: 'America/Scoresbysund' },
    'KIRIBATI': { PHX: 'Pacific/Kanton', LIN: 'Pacific/Kiritimati' },
    'MICRONESIA': { TRK: 'Pacific/Chuuk', KSA: 'Pacific/Kosrae' },
    'MONGOLIA': { HOV: 'Asia/Hovd' },
    'PAPUA NEW GUINEA': { NSB: 'Pacific/Bougainville' }
};

if (typeof window !== 'undefined') {
    window.lookupCountry = lookupCountry;
    window.lookupTimezone = lookupTimezone;
    window.lookupTimezoneState = lookupTimezoneState;
}
